# Generated by Django 2.1.7 on 2019-03-05 21:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='rides',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
