# Generated by Django 2.2 on 2019-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0002_auto_20190305_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='user',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
