# Generated by Django 2.2 on 2019-04-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0003_rides_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='user',
            field=models.CharField(default='admin', editable=False, max_length=30),
        ),
    ]
