# Generated by Django 2.2 on 2019-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0004_auto_20190412_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='destination_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rides',
            name='location_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='rides',
            name='user',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
