# Generated by Django 2.2 on 2019-05-10 11:16

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0005_auto_20190505_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+40745854575', max_length=128, region=None, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rides',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rides',
            name='ride_date',
            field=models.DateTimeField(blank=True, default='2020-09-12 21:25'),
            preserve_default=False,
        ),
    ]
