# Generated by Django 2.2 on 2019-05-10 11:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0006_auto_20190510_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
