# Generated by Django 2.2 on 2019-05-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0007_auto_20190510_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
