# Generated by Django 2.2 on 2019-05-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0009_auto_20190510_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
