# Generated by Django 2.2 on 2019-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0011_auto_20190514_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='ride_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
