# Generated by Django 2.2 on 2019-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0012_auto_20190514_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!..Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!', max_length=400),
            preserve_default=False,
        ),
    ]
