# Generated by Django 2.2 on 2019-06-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0014_localusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='localusers',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
