# Generated by Django 2.2 on 2019-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0015_localusers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='localusers',
            name='department',
            field=models.CharField(default='Free', max_length=100),
            preserve_default=False,
        ),
    ]
