# Generated by Django 2.2 on 2019-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeRides', '0017_rides_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='seats',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
